#spring.application.name=patient-service
#spring.config.import=optional:configserver:http://localhost:8888
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: patient-service