server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  config:
    import: classpath:/configurations/shared-datasource.yml
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/auth/** , /api/v1/user/**
        - id: patient-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/patient/**
          filters:
            - AuthFilter
        - id: staff-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/doctors/**
          filters:
            - AuthFilter
        - id: auth-service-docs
          uri: http://localhost:8000
          predicates:
            - Path=/auth-service/v3/api-docs
        - id: patient-service-docs
          uri: http://localhost:9091
          predicates:
            - Path=/patient-service/v3/api-docs
        - id: staff-service-docs
          uri: http://localhost:8050
          predicates:
            - Path=/staff-service/v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /auth-service/v3/api-docs
        name: Auth Service
      - url: /patient-service/v3/api-docs
        name: Patient Service
      - url: /staff-service/v3/api-docs
        name: Staff Service

management:
  tracing:
    sampling:
      probability: 1.0
