spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
        - id: patient-service
          uri: lb:http://PATIENT-SERVICE
          predicates:
            - Path=/api/v1/patient/**
server:
  port: 8080
