server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/auth/**
        - id: patient-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/patient/**
        - id: staff-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/staff/**

management:
  tracing:
    sampling:
      probability: 1.0
