spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_wflxLn-5DmvsoMpT-6k@mysql-17425251-hoanglong434gl-d94b.c.aivencloud.com:17032/devenv?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_wflxLn-5DmvsoMpT-6k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    jwt:
      secret: bXlTdXBlclNlY3JldEtleUhlcmU1ODQyMTIzIT8kJCY=
      expiration: 86400000 #(24 giờ)